on:
  push:
    branches:
    - main
jobs: 
  dependencies: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4.1.0
        with: 
          node-version: 23.5.0
          cache: yarn
          cache-dependency-path: yarn.lock
      - run:  npm i yarn
